image: registry.gitlab.tugraz.at/dbp/educational-credentials/educred/main:v1

cache:
  key: $CI_PROJECT_PATH
  paths:
    - _npm_cache

before_script:
  - 'git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tugraz.at/".insteadOf "git@gitlab.tugraz.at:"'
  - git submodule sync
  - git submodule update --init
  - npm config set cache "$CI_PROJECT_DIR/_npm_cache"

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm ci
    - APP_ENV=development npm run build
    - npm run test-full

linting:
  stage: test
  allow_failure: true
  script:
    - npm ci
    - npm run lint

deploy:
  stage: deploy
  except:
    - schedules
  only:
    refs:
      - main
      - demo
      - production
  inherit:
    variables: false
  variables:
    UPSTREAM_PROJECT_PATH: ${CI_PROJECT_PATH}
    UPSTREAM_COMMIT_BRANCH: ${CI_COMMIT_BRANCH}
    UPSTREAM_COMMIT_SHA: ${CI_COMMIT_SHA}
  trigger:
    project: dbp/deployer
    strategy: depend
